In [21]:
import numpy as np

def gauss_elim(A):
    if(not isinstance(A, np.matrix) or not A.ndim==2 or not A.shape[0]==A.shape[1]):
        return 0
    row = 0
    #Doprowadzanie macierzy do postaci trójkątnej dolnej
    while(row < A.shape[0]-1):
        i = row+1
        while(A.item(row, row)==0):
            if(i>A.shape[0]):
                break
            A[[row, i]] = A[[i,row]]
            i+=1
        
        while(i < A.shape[0]):
            A[i]-=(A[row]/A.item(row, row))*A.item(i, row)
            i+=1
        row+=1
    #Doprowadzanie macierzy do postaci trójkątnej górnej 
    while(row>0):
        i=row-1
        while(i>=0):
            A[i]-=(A[row]/A.item(row, row))*A.item(i, row)
            i-=1
        row-=1
    return A


A = np.matrix([[0.0001, -5.0300, 5.8090, 7.8320],
              [2.2660, 1.9950,  1.2120, 8.0080],
              [8.8500, 5.6810,  4.5520, 1.3020],
              [6.7750, -2.253,  2.9080, 3.9700]])

print(A)

gauss_elim(A)

print(A)
#Jak widać dziaa

[[ 1.000e-04 -5.030e+00  5.809e+00  7.832e+00]
 [ 2.266e+00  1.995e+00  1.212e+00  8.008e+00]
 [ 8.850e+00  5.681e+00  4.552e+00  1.302e+00]
 [ 6.775e+00 -2.253e+00  2.908e+00  3.970e+00]]
[[ 1.00000000e-04  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.13981795e+05  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -2.61893648e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  9.68447519e+01]]
